Improved script.

diff --git a/src/system-maintenance.d/30-rsplib b/src/system-maintenance.d/30-rsplib
--- a/src/system-maintenance.d/30-rsplib
+++ b/src/system-maintenance.d/30-rsplib
@@ -1,6 +1,19 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# ##########################################################################
 #
-# Print installed NorNet packages
+#              //===//   //=====   //===//   //       //   //===//
+#             //    //  //        //    //  //       //   //    //
+#            //===//   //=====   //===//   //       //   //===<<
+#           //   \\         //  //        //       //   //    //
+#          //     \\  =====//  //        //=====  //   //===//   Version III
+#
+#             ###################################################
+#           ======  D E M O N S T R A T I O N   S Y S T E M  ======
+#             ###################################################
+#
+# ############# An Efficient RSerPool Prototype Implementation #############
+#
+# RSPLIB System-Info system-info.d Script
 # Copyright (C) 2013-2025 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
@@ -18,10 +31,41 @@
 #
 # Contact: thomas.dreibholz@gmail.com
 
-fullPackageList="$1"
+# Bash options:
+set -eu
 
-echo "====== Installed RSPLIB Software ============================================="
-grep "^rsplib-" ${fullPackageList}
-grep "^rserpooldemo-" ${fullPackageList}
+# Helper function library -> just return when it is not available.
+# Exit code 0 will let System-Info continue with the next script!
+# shellcheck disable=SC1091
+. "$(dirname "$0")/banner-helper" || exit 0
 
-exit 0
+
+# ====== Print banner =======================================================
+
+RSERPOOLDEMO_VERSION=""
+if [ -e /etc/simulamet/rserpooldemo-version ] ; then
+   RSERPOOLDEMO_VERSION="$(cat /etc/simulamet/rserpooldemo-version)"
+fi
+
+echo -en "\x1b[1;34m"
+separator "  " "═" "  "
+echo -en "\x1b[1;31m"
+center " ____  ____  ____  _     ___ ____  "
+center "|  _ \/ ___||  _ \| |   |_ _| __ ) "
+center "| |_) \___ \| |_) | |    | ||  _ \ "
+center "|  _ < ___) |  __/| |___ | || |_) |"
+center "|_| \_\____/|_|   |_____|___|____/ "
+echo ""
+center "◀◀◀ RSPLIB Project at the University of Duisburg-Essen ▶▶▶"
+echo -en "\x1b[1;34m"
+if [ "${RSERPOOLDEMO_VERSION}" != "" ] ; then
+   echo ""
+   center "${RSERPOOLDEMO_VERSION}"
+fi
+separator "  " "═" "  "
+echo -e "\x1b[0m"
+
+
+exit 1   # With exit code 1, no further files in /etc/system-info.d are processed!
+
+# Use exit code 0 to process further files!
