git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rserpooldemo@1327 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/bin/PlanetLabScenario-StopAll b/bin/PlanetLabScenario-StopAll
--- a/bin/PlanetLabScenario-StopAll
+++ b/bin/PlanetLabScenario-StopAll
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # $Id$
 # ***************************************************************************
 # *   The RSerPool Demo System                                              *
@@ -21,52 +21,22 @@
 # *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 # ***************************************************************************
 
-if [ $# -lt 5 ] ; then
-   echo >&2 "Usage: RemoteComponentControl [User Configuration File] [Host] [Scenario Configuration File] [Identifier] [start|stop|kill|stopall|killall|restart|status|log|monitor] {Arguments ...}"
+if [ $# -lt 1 ] ; then
+   echo >&2 "Usage: PlanetLabScenario-StopAll [stop|kill]"
    exit 1
 fi
 
 
-# ====== Get configuration ==================================================
-CC_REMOTECONFIG=$1
-CC_HOST=$2
-CC_CONFIGFILE=$3
-CC_IDENTIFIER=$4
-CC_COMMAND=$5
-shift ; shift ; shift ; shift ; shift
-CC_MISCARGS=$@
-
-if [ ! -e "$CC_REMOTECONFIG" ] ; then
-   echo >&2 "ERROR: Configuration file $CC_REMOTECONFIG does not exist!"
-   exit 1
-fi
-
-. ./$CC_REMOTECONFIG
-CC_LOCALUSER="`whoami`"
-if [ "x$CC_PATH" = "x" ] ; then
-   CC_PATH="`pwd | sed -e \"s/$CC_LOCALUSER/$CC_REMOTEUSER/g\"`"
-fi
-
-eval CC_HOST=$CC_HOST
-if [ "x$CC_HOST" = "x" ] ; then
-   echo >&2 "ERROR: No host name specified! Check evaluation string!"
+if [ "x$1" = "xstop" ] ; then
+   command=stopall
+elif [ "x$1" = "xkill" ] ; then
+   command=killall
+else
+   echo >&2 "ERROR: Bad command $1!"
    exit 1
 fi
 
 
-command="$CC_REMOTEPRECOMMAND nohup ./ComponentControl $CC_CONFIGFILE $CC_IDENTIFIER $CC_COMMAND $CC_MISCARGS >/dev/null 2>/dev/null &"
-
-
-echo "Contacting $CC_REMOTEUSER@$CC_HOST using key $CC_REMOTEKEY ..."
-ssh -i $CC_REMOTEKEY $CC_SSHOPT $CC_REMOTEUSER@$CC_HOST "
-if [ ! -e $CC_PATH ] ; then
-   echo \"ERROR: Directory $CC_PATH does not exist on host $CC_HOST!\"
-   exit 1
-fi &&
-cd $CC_PATH && \
-if [ ! -e ComponentControl ] ; then
-   echo \"ERROR: ComponentControl not found in directory $CC_PATH of host $CC_HOST!\"
-   exit 1
-fi &&
-echo \"$command\" &&
-$command"
+./ComponentControl ./PlanetLabScenario.config PU 0 killall
+./ComponentControl ./PlanetLabScenario.config PE 0 $command
+./ComponentControl ./PlanetLabScenario.config PR 0 $command
