Improved error handling.

diff --git a/background/gimp-scripts/Make-OldPhoto b/background/gimp-scripts/Make-OldPhoto
--- a/background/gimp-scripts/Make-OldPhoto
+++ b/background/gimp-scripts/Make-OldPhoto
@@ -58,5 +58,10 @@ fi
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C gimp --new-instance --no-interface --no-splash --batch - 2>/dev/null | \
-       ( grep -vE "^ts>|^Copyright|^Welcome|^$" || true )
+) | env LANG=C gimp --new-instance --no-interface --no-splash --batch - 2>&1 | \
+       ( grep -vE "^ts>|^Copyright|^Welcome|GLib-GObject-WARNING|^$" || true )
+
+if [ ! -e "$OUTPUTFILENAME" ] ; then
+   echo >&2 "ERROR: $OUTPUTFILENAME has not been produced. Something went wrong!"
+   exit 1
+fi
