Updated GIMP Scripts.

diff --git a/src/background/gimp-scripts/gs-bumpmap b/src/background/gimp-scripts/gs-bumpmap
--- a/src/background/gimp-scripts/gs-bumpmap
+++ b/src/background/gimp-scripts/gs-bumpmap
@@ -35,14 +35,14 @@ set -euo pipefail
 # ###### Usage ##############################################################
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename [-C|--compensate-darkening on|off] [-I|--invert on|off] [-T|--tiled on|off] [-A|--azimut bearing] [-E|--elevation bearing] [-D|--depth depth] [-X|--offset-x value] [-Y|--offset-y value] [-W|--waterlevel level] [-B|--ambient factor] [-H|--hue-range all|red|yellow|green|cyan|blue|magenta] [-O|--hue-offset degrees] [-L|--lightness adjustment] [-S|--saturation adjustment] [-V|--overlap overlap] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
+   echo >&2 "Usage: $0 input_filename output_filename [-C|--compensate-darkening on|off] [-I|--invert on|off] [-T|--tiled on|off] [-A|--azimuth bearing] [-E|--elevation bearing] [-D|--depth depth] [-X|--offset-x value] [-Y|--offset-y value] [-W|--waterlevel level] [-B|--ambient factor] [-H|--hue-range all|red|yellow|green|cyan|blue|magenta] [-O|--hue-offset degrees] [-L|--lightness adjustment] [-S|--saturation adjustment] [-V|--overlap overlap] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
    exit "${exitCode}"
 }
 
 
 # ###### Version ############################################################
 version () {
-   echo "gs-bumpmap @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   echo "gs-bumpmap 2.7.5~rc0"
    exit 0
 }
 
@@ -51,9 +51,33 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
-options="$(${GETOPT} -o C:I:T:A:E:D:X:Y:W:B:H:O:L:S:V:wqhv --long compensate-darkening:,invert:,tiled:,azimut:,elevation:,depth:,offset-x:,offset-y:,waterlevel:,ambient:,hue-range:,hue-offset:,lightness:,saturation:,overlap:,verbose,quiet,help,version -a -- "$@")"
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o C:I:T:A:E:D:X:Y:W:B:H:O:L:S:V:wqhv --long compensate-darkening:,invert:,tiled:,azimuth:,elevation:,depth:,offset-x:,offset-y:,waterlevel:,ambient:,hue-range:,hue-offset:,lightness:,saturation:,overlap:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
    usage 1
@@ -73,7 +97,7 @@ declare -A hueRanges=(
 COMPENSATE="TRUE"
 INVERT="FALSE"
 TILED="FALSE"
-AZIMUT=135.0
+AZIMUTH=135.0
 ELEVATION=45.0
 DEPTH=20
 OFFSET_X=0
@@ -89,166 +113,171 @@ VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
       -C | --compensate-darkening)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         COMPENSATE="$2"
+         shift
+         if [[ "${COMPENSATE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             COMPENSATE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${COMPENSATE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             COMPENSATE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -C|--compensate-darkening!"
+            echo >&2 "ERROR: Invalid value ${COMPENSATE} for -C|--compensate-darkening!"
             exit 1
          fi
-         shift 2
          ;;
       -I | --invert)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
-            TILED="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
-            TILED="FALSE"
+         INVERT="$2"
+         shift
+         if [[ "${INVERT}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+            INVERT="TRUE"
+         elif [[ "${INVERT}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+            INVERT="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -I|--invert!"
+            echo >&2 "ERROR: Invalid value ${INVERT} for -I|--invert!"
             exit 1
          fi
-         shift 2
          ;;
       -T | --tiled)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         TILED="$2"
+         shift
+         if [[ "${TILED}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             TILED="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${TILED}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             TILED="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -T|--tiled!"
+            echo >&2 "ERROR: Invalid value ${TILED} for -T|--tiled!"
             exit 1
          fi
-         shift 2
          ;;
-      -A | --azimut)
-         AZIMUT="$2"
-         if [[ ! "${AZIMUT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$ ]] || \
-            awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
-            echo >&2 "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
+      -A | --azimuth)
+         AZIMUTH="$2"
+         shift
+         if [[ ! "${AZIMUTH}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$ ]] || \
+            awk "BEGIN { exit ( ($AZIMUTH < 0.0) || ($AZIMUTH > 360.0) ? 0 : 1) }" ; then
+            echo >&2 "ERROR: Invalid value ${AZIMUTH} for -A|--azimuth!"
             exit 1
          fi
-         shift 2
          ;;
       -E | --elevation)
          ELEVATION="$2"
+         shift
          if [[ ! "${ELEVATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
             exit 1
          fi
-         shift 2
          ;;
       -D | --depth)
+         DEPTH="$2"
+         shift
          if [[ ! "${DEPTH}" =~ ^[0-9]+$ ]] || [ "${DEPTH}" -lt 1 ] || [ "${DEPTH}" -gt 65 ] ; then
             echo >&2 "ERROR: Invalid value ${DEPTH} for -D|--depth!"
             exit 1
          fi
-         shift 2
          ;;
       -X | --offset-x)
          OFFSET_X="$2"
+         shift
          if [[ ! "${OFFSET_X}" =~ ^[0-9]+$ ]] || [ "${OFFSET_X}" -lt -20000 ] || [ "${OFFSET_X}" -gt 20000 ] ; then
             echo >&2 "ERROR: Invalid value ${OFFSET_X} for -X|--offset-x!"
             exit 1
          fi
-         shift 2
          ;;
       -Y | --offset-y)
          OFFSET_Y="$2"
+         shift
          if [[ ! "${OFFSET_Y}" =~ ^[0-9]+$ ]] || [ "${OFFSET_Y}" -lt -20000 ] || [ "${OFFSET_Y}" -gt 20000 ] ; then
             echo >&2 "ERROR: Invalid value ${OFFSET_Y} for -Y|--offset-y!"
             exit 1
          fi
-         shift 2
          ;;
       -W | --waterlevel)
          WATERLEVEL="$2"
+         shift
          if [[ ! "${WATERLEVEL}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($WATERLEVEL < 0.0) || ($WATERLEVEL > 1.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${WATERLEVEL} for -W|--waterlevel!"
             exit 1
          fi
-         shift 2
          ;;
       -B | --ambient)
          AMBIENT="$2"
+         shift
          if [[ ! "${AMBIENT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($AMBIENT < 0.0) || ($AMBIENT > 1.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${AMBIENT} for -B|--ambient!"
             exit 1
          fi
-         shift 2
          ;;
 
       -H | --hue-range)
-         if [[ ! -v hueRanges["$2"] ]] ; then
-            echo >&2 "ERROR: Invalid value $2 for -H|--hue-range!"
+         HUE_RANGE="$2"
+         shift
+         if [[ ! -v hueRanges["${HUE_RANGE}"] ]] ; then
+            echo >&2 "ERROR: Invalid value ${HUE_RANGE} for -H|--hue-range!"
             exit 1
          fi
-         HUE_RANGE="${hueRanges[$2]}"
-         shift 2
+         HUE_RANGE="${hueRanges["${HUE_RANGE}"]}"
          ;;
       -O | --hue-offset)
          HUE_OFFSET="$2"
+         shift
          if [[ ! "${HUE_OFFSET}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($HUE_OFFSET < -180.0) || ($HUE_OFFSET > 180.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${HUE_OFFSET} for -O|--hue-offset!"
             exit 1
          fi
-         shift 2
          ;;
       -L | --lightness)
          LIGHTNESS="$2"
+         shift
          if [[ ! "${LIGHTNESS}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($LIGHTNESS < -100.0) || ($LIGHTNESS > 100.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${LIGHTNESS} for -L|--lightness!"
             exit 1
          fi
-         shift 2
          ;;
       -S | --saturation)
          SATURATION="$2"
+         shift
          if [[ ! "${SATURATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($SATURATION < -100.0) || ($SATURATION > 100.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${SATURATION} for -S|--saturation!"
             exit 1
          fi
-         shift 2
          ;;
       -V | --overlap)
          OVERLAP="$2"
+         shift
          if [[ ! "${OVERLAP}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($OVERLAP < 0.0) || ($OVERLAP > 100.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${OVERLAP} for -V|--overlap!"
             exit 1
          fi
-         shift 2
          ;;
 
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -264,14 +293,17 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || command -v /Applications/GIMP.app/Contents/MacOS/gimp-console-3 || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
-   echo >&2 "ERROR: GIMP is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
-   echo >&2 "* Fedora:  sudo dnf install -y gimp"
-   echo >&2 "* SuSE     sudo zypper install -y gimp"
-   echo >&2 "* Alpine:  sudo apk add gimp"
-   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
+   echo >&2 "ERROR: GIMP is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y gimp"
+   echo >&2 " * Fedora:        sudo dnf install -y gimp"
+   echo >&2 " * SuSE           sudo zypper install -y gimp"
+   echo >&2 " * Alpine:        sudo apk add gimp"
+   echo >&2 " * FreeBSD:       sudo pkg install -y gimp3-app"
+   echo >&2 " * NetBSD:        sudo pkgin -y install gimp"
+   echo >&2 " * OpenBSD:       sudo pkg_add gimp"
+   echo >&2 " * Apple:         brew install gimp"
    exit 1
 fi
 GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
@@ -284,7 +316,7 @@ else
 fi
 
 # This script does not use fonts, or gradients/palettes/brushes:
-GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts"
 
 
 # ====== Call GIMP ==========================================================
@@ -293,36 +325,36 @@ rm -f "${OUTPUT_FILENAME}"
 ( cat <<EOF
 (let*
    ; ------ Initialise and load image ---------------------------------------
-   ((inputFileName    "${INPUT_FILENAME}")
-    (outputFileName   "${OUTPUT_FILENAME}")
-    (azimut           ${AZIMUT})
-    (elevation        ${ELEVATION})
-    (depth            ${DEPTH})
-    (offsetX          ${OFFSET_X})
-    (offsetY          ${OFFSET_Y})
-    (waterlevel       ${WATERLEVEL})
-    (ambient          ${AMBIENT})
-    (compensate       ${COMPENSATE})
-    (invert           ${INVERT})
-    (tiled            ${TILED})
-    (hueRange         ${HUE_RANGE})
-    (hueOffset        ${HUE_OFFSET})
-    (lightness        ${LIGHTNESS})
-    (saturation       ${SATURATION})
-    (overlap          ${OVERLAP})
-    (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
-    (imageType        (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New GIMP 3.0 API:
-                         (car (gimp-image-get-base-type image))
-                         ; Old GIMP 2.x API:
-                         (car (gimp-image-base-type image)))
-                      )
-    (layer            (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New GIMP 3.0 API:
-                         (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
-                         ; Old GIMP 2.x API:
-                         (car (gimp-image-get-active-layer image)))
-                      )
+   ((inputFileName  "${INPUT_FILENAME}")
+    (outputFileName "${OUTPUT_FILENAME}")
+    (azimuth        ${AZIMUTH})
+    (elevation      ${ELEVATION})
+    (depth          ${DEPTH})
+    (offsetX        ${OFFSET_X})
+    (offsetY        ${OFFSET_Y})
+    (waterlevel     ${WATERLEVEL})
+    (ambient        ${AMBIENT})
+    (compensate     ${COMPENSATE})
+    (invert         ${INVERT})
+    (tiled          ${TILED})
+    (hueRange       ${HUE_RANGE})
+    (hueOffset      ${HUE_OFFSET})
+    (lightness      ${LIGHTNESS})
+    (saturation     ${SATURATION})
+    (overlap        ${OVERLAP})
+    (image          (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
+    (imageType      (if (not (defined? 'gimp-image-get-active-layer))
+                       ; New GIMP 3.0 API:
+                       (car (gimp-image-get-base-type image))
+                       ; Old GIMP 2.x API:
+                       (car (gimp-image-base-type image)))
+                    )
+    (layer          (if (not (defined? 'gimp-image-get-active-layer))
+                       ; New GIMP 3.0 API:
+                       (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
+                       ; Old GIMP 2.x API:
+                       (car (gimp-image-get-active-layer image)))
+                    )
    )
 
    ; ------ Apply filter ----------------------------------------------------
@@ -341,7 +373,7 @@ rm -f "${OUTPUT_FILENAME}"
    (if (defined? 'gimp-drawable-merge-new-filter)
       (begin  ; New GIMP >= 3.0 API:
         (gimp-drawable-merge-new-filter layer "gegl:bump-map" 0 LAYER-MODE-REPLACE 1.0
-            "azimuth"    azimut
+            "azimuth"    azimuth
             "elevation"  elevation
             "depth"      depth
             "offset-x"   offsetX
@@ -356,7 +388,7 @@ rm -f "${OUTPUT_FILENAME}"
       )
       (begin  ; Old GIMP < 3.0 API:
          (plug-in-bump-map RUN-NONINTERACTIVE image layer layer
-           azimut elevation depth
+           azimuth elevation depth
            offsetX offsetY waterlevel ambient
            compensate invert tiled)
       )
@@ -414,7 +446,7 @@ EOF
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
diff --git a/src/background/gimp-scripts/gs-caption b/src/background/gimp-scripts/gs-caption
--- a/src/background/gimp-scripts/gs-caption
+++ b/src/background/gimp-scripts/gs-caption
@@ -35,14 +35,14 @@ set -euo pipefail
 # ###### Usage ##############################################################
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 output_filename caption_width caption_height caption_text [-F|--font-name font] [-S|--font-size percentage] [-f|--foreground color] [-b|--background color] [|-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
+   echo >&2 "Usage: $0 output_filename caption_width caption_height caption_text [-F|--font-name font] [-S|--font-size percentage] [-f|--foreground color] [-b|--background color] [-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
    exit "${exitCode}"
 }
 
 
 # ###### Version ############################################################
 version () {
-   echo "gs-caption @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   echo "gs-caption 2.7.5~rc0"
    exit 0
 }
 
@@ -51,8 +51,32 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o F:S:f:b:t:wqhv --long font-name:,font-size:,foreground:,background:,transparency:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -70,64 +94,63 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -F | --font-name)
          FONT_NAME="$2"
-         shift 2
+         shift
          ;;
       -S | --font-size)
          FONT_SIZE="$2"
+         shift
          if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] || [ "${FONT_SIZE}" -gt 100 ] ; then
-            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
+            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -S|--font-size!"
             exit 1
          fi
-         shift 2
          ;;
       -f | --foreground)
          COLOR_FOREGROUND="$2"
+         shift
          if [[ ! "${COLOR_FOREGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
             echo >&2 "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
             exit 1
          fi
-         shift 2
          ;;
       -b | --background)
          COLOR_BACKGROUND="$2"
+         shift
          if [[ ! "${COLOR_BACKGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
             echo >&2 "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
             exit 1
          fi
-         shift 2
          ;;
       -t | --transparency)
          TRANSPARENCY="$2"
+         shift
          if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ]; then
             echo >&2 "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
             exit 1
          fi
-         TRANSPARENCY="$2"
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 4 ] ; then
@@ -149,14 +172,17 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || command -v /Applications/GIMP.app/Contents/MacOS/gimp-console-3 || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
-   echo >&2 "ERROR: GIMP is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
-   echo >&2 "* Fedora:  sudo dnf install -y gimp"
-   echo >&2 "* SuSE     sudo zypper install -y gimp"
-   echo >&2 "* Alpine:  sudo apk add gimp"
-   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
+   echo >&2 "ERROR: GIMP is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y gimp"
+   echo >&2 " * Fedora:        sudo dnf install -y gimp"
+   echo >&2 " * SuSE           sudo zypper install -y gimp"
+   echo >&2 " * Alpine:        sudo apk add gimp"
+   echo >&2 " * FreeBSD:       sudo pkg install -y gimp3-app"
+   echo >&2 " * NetBSD:        sudo pkgin -y install gimp"
+   echo >&2 " * OpenBSD:       sudo pkg_add gimp"
+   echo >&2 " * Apple:         brew install gimp"
    exit 1
 fi
 GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
@@ -167,9 +193,6 @@ else
    # GIMP 3.x:
    GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 fi
-
-# This script does not use gradients/palettes/brushes:
-GIMP_OPTIONS="${GIMP_OPTIONS} --no-data"
 
 
 # ====== Call GIMP ==========================================================
@@ -215,7 +238,7 @@ rm -f "${OUTPUT_FILENAME}"
       (set! captionFont "${FONT_NAME}"))
    ; (newline) (display "captionFont=") (display captionFont) (newline)
    (if (and (not (defined? 'gimp-image-get-active-layer)) (= captionFont -1)) (
-      (gimp-message "ERROR: Font \"${FONT_NAME}\" is not available! Check installed fonts with fc-list!")
+      (gimp-message "ERROR: Font \"${FONT_NAME}\" is not available! Check installed fonts with gs-list-fonts!")
       (quit FALSE)
    ))
 
@@ -286,7 +309,7 @@ EOF
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
diff --git a/src/background/gimp-scripts/gs-clothify b/src/background/gimp-scripts/gs-clothify
--- a/src/background/gimp-scripts/gs-clothify
+++ b/src/background/gimp-scripts/gs-clothify
@@ -35,14 +35,14 @@ set -euo pipefail
 # ###### Usage ##############################################################
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename [-X|--blur-x value] [-Y|--blur-y value] [-A|--azimut bearing] [-E|--elevation bearing] [-D|--depth depth] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
+   echo >&2 "Usage: $0 input_filename output_filename [-X|--blur-x value] [-Y|--blur-y value] [-A|--azimuth bearing] [-E|--elevation bearing] [-D|--depth depth] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
    exit "${exitCode}"
 }
 
 
 # ###### Version ############################################################
 version () {
-   echo "gs-clothify @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   echo "gs-clothify 2.7.5~rc0"
    exit 0
 }
 
@@ -51,9 +51,33 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
-options="$(${GETOPT} -o X:Y:A:E:D:wqhv --long blur-x:,blur-y:,azimut:,elevation:,depth:,verbose,quiet,help,version -a -- "$@")"
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o X:Y:A:E:D:wqhv --long blur-x:,blur-y:,azimuth:,elevation:,depth:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
    usage 1
@@ -62,7 +86,7 @@ eval set -- "${options}"
 
 BLUR_X=3
 BLUR_Y=3
-AZIMUT=135.0
+AZIMUTH=135.0
 ELEVATION=45.0
 DEPTH=5
 VERBOSE=0
@@ -70,68 +94,69 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -X | --blur-x)
          BLUR_X="$2"
+         shift
          if [[ ! "${BLUR_X}" =~ ^[0-9]+$ ]] || [ "${BLUR_X}" -lt 3 ] || [ "${BLUR_X}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${BLUR_X} for -X|--blur-x!"
             exit 1
          fi
-         shift 2
          ;;
       -Y | --blur-y)
          BLUR_Y="$2"
+         shift
          if [[ ! "${BLUR_Y}" =~ ^[0-9]+$ ]] || [ "${BLUR_Y}" -lt 3 ] || [ "${BLUR_Y}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${BLUR_Y} for -Y|--blur-y!"
             exit 1
          fi
-         shift 2
          ;;
-      -A | --azimut)
-         AZIMUT="$2"
-         if [[ ! "${AZIMUT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
-            awk "BEGIN { exit ( ($AZIMUT < 0.0) || ($AZIMUT > 360.0) ? 0 : 1) }" ; then
-            echo >&2 "ERROR: Invalid value ${AZIMUT} for -A|--azimut!"
+      -A | --azimuth)
+         AZIMUTH="$2"
+         shift
+         if [[ ! "${AZIMUTH}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
+            awk "BEGIN { exit ( ($AZIMUTH < 0.0) || ($AZIMUTH > 360.0) ? 0 : 1) }" ; then
+            echo >&2 "ERROR: Invalid value ${AZIMUTH} for -A|--azimuth!"
             exit 1
          fi
-         shift 2
          ;;
       -E | --elevation)
          ELEVATION="$2"
+         shift
          if [[ ! "${ELEVATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($ELEVATION < 0.5) || ($ELEVATION > 90.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${ELEVATION} for -E|--elevation!"
             exit 1
          fi
-         shift 2
          ;;
       -D | --depth)
+         DEPTH="$2"
+         shift
          if [[ ! "${DEPTH}" =~ ^[0-9]+$ ]] || [ "${DEPTH}" -lt 1 ] || [ "${DEPTH}" -gt 65 ] ; then
             echo >&2 "ERROR: Invalid value ${DEPTH} for -D|--depth!"
             exit 1
          fi
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -147,14 +172,17 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || command -v /Applications/GIMP.app/Contents/MacOS/gimp-console-3 || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
-   echo >&2 "ERROR: GIMP is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
-   echo >&2 "* Fedora:  sudo dnf install -y gimp"
-   echo >&2 "* SuSE     sudo zypper install -y gimp"
-   echo >&2 "* Alpine:  sudo apk add gimp"
-   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
+   echo >&2 "ERROR: GIMP is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y gimp"
+   echo >&2 " * Fedora:        sudo dnf install -y gimp"
+   echo >&2 " * SuSE           sudo zypper install -y gimp"
+   echo >&2 " * Alpine:        sudo apk add gimp"
+   echo >&2 " * FreeBSD:       sudo pkg install -y gimp3-app"
+   echo >&2 " * NetBSD:        sudo pkgin -y install gimp"
+   echo >&2 " * OpenBSD:       sudo pkg_add gimp"
+   echo >&2 " * Apple:         brew install gimp"
    exit 1
 fi
 GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
@@ -167,7 +195,7 @@ else
 fi
 
 # This script does not use fonts, or gradients/palettes/brushes:
-GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts"
 
 
 # ====== Call GIMP ==========================================================
@@ -176,26 +204,26 @@ rm -f "${OUTPUT_FILENAME}"
 ( cat <<EOF
 (let*
    ; ------ Initialise and load image ---------------------------------------
-   ((inputFileName    "${INPUT_FILENAME}")
-    (outputFileName   "${OUTPUT_FILENAME}")
-    (blurX            ${BLUR_X})
-    (blurY            ${BLUR_Y})
-    (azimut           ${AZIMUT})
-    (elevation        ${ELEVATION})
-    (depth            ${DEPTH})
-    (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
-    (imageType        (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New GIMP 3.0 API:
-                         (car (gimp-image-get-base-type image))
-                         ; Old GIMP 2.x API:
-                         (car (gimp-image-base-type image)))
-                      )
-    (layer            (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New GIMP 3.0 API:
-                         (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
-                         ; Old GIMP 2.x API:
-                         (car (gimp-image-get-active-layer image)))
-                      )
+   ((inputFileName  "${INPUT_FILENAME}")
+    (outputFileName "${OUTPUT_FILENAME}")
+    (blurX          ${BLUR_X})
+    (blurY          ${BLUR_Y})
+    (azimuth        ${AZIMUTH})
+    (elevation      ${ELEVATION})
+    (depth          ${DEPTH})
+    (image          (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
+    (imageType      (if (not (defined? 'gimp-image-get-active-layer))
+                       ; New GIMP 3.0 API:
+                       (car (gimp-image-get-base-type image))
+                       ; Old GIMP 2.x API:
+                       (car (gimp-image-base-type image)))
+                    )
+    (layer          (if (not (defined? 'gimp-image-get-active-layer))
+                       ; New GIMP 3.0 API:
+                       (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
+                       ; Old GIMP 2.x API:
+                       (car (gimp-image-get-active-layer image)))
+                    )
    )
 
    ; ------ Apply filter ----------------------------------------------------
@@ -205,11 +233,11 @@ rm -f "${OUTPUT_FILENAME}"
 
    (cond( (not(defined? 'plug-in-bump-map))
       ; New GIMP 3.0 API:
-      (script-fu-clothify image (vector layer) blurX blurY azimut elevation depth)
+      (script-fu-clothify image (vector layer) blurX blurY azimuth elevation depth)
    )
    (else
       ; Old GIMP 2.x API:
-      (script-fu-clothify image layer blurX blurY azimut elevation depth)
+      (script-fu-clothify image layer blurX blurY azimuth elevation depth)
    ))
 
    ; ------ Save result -----------------------------------------------------
@@ -252,7 +280,7 @@ EOF
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
diff --git a/src/background/gimp-scripts/gs-glossytext b/src/background/gimp-scripts/gs-glossytext
--- a/src/background/gimp-scripts/gs-glossytext
+++ b/src/background/gimp-scripts/gs-glossytext
@@ -13,6 +13,10 @@
 # GIMP Scripts
 # Copyright (C) 2013-2026 by Thomas Dreibholz
 #
+# Based on glossy-300.scm from https://github.com/vitforlinux-gimp/scm:
+# Copyright (C) 1995 Spencer Kimball and Peter Mattis
+# Copyright (C) 1998 Hrvoje Horvat
+#
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
@@ -35,14 +39,14 @@ set -euo pipefail
 # ###### Usage ##############################################################
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 filename text [-F|--font-name font] [-S|--font-size size] [-G|--blend-gradient-text gradient] [-g|--blend-gradient-text-reverse on|off] [-L|--blend-gradient-outline gradient] [-l|--blend-gradient-outline-reverse on|off] [-O|--outline-size size] [-B|--background-color color] [-I|--pattern-text pattern] [-i|--use-pattern-text on|off] [-J|--pattern-outline pattern] [-j|--use-pattern-outline on|off] [-R|--pattern-overlay pattern] [-r|--use-pattern-overlay on|off] [-s|--use-shadow on|off] [-X|--shadow-offset-x offset] [-Y|--shadow-offset-y offset] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
+   echo >&2 "Usage: $0 output_filename text [-F|--font-name font] [-S|--font-size size] [-G|--blend-gradient-text gradient] [-g|--blend-gradient-text-reverse on|off] [-L|--blend-gradient-outline gradient] [-l|--blend-gradient-outline-reverse on|off] [-O|--outline-size size] [-B|--background-color color] [-I|--pattern-text pattern] [-i|--use-pattern-text on|off] [-J|--pattern-outline pattern] [-j|--use-pattern-outline on|off] [-R|--pattern-overlay pattern] [-r|--use-pattern-overlay on|off] [-s|--use-shadow on|off] [-X|--shadow-offset-x offset] [-Y|--shadow-offset-y offset] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
    exit "${exitCode}"
 }
 
 
 # ###### Version ############################################################
 version () {
-   echo "gs-glossytext @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   echo "gs-glossytext 2.7.5~rc0"
    exit 0
 }
 
@@ -51,8 +55,32 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o F:S:G:g:L:l:O:B:I:i:J:j:R:r:s:X:Y:wqhv --long font-name:,font-size:,blend-gradient-text:,blend-gradient-text-reverse:,blend-gradient-outline:,blend-gradient-outline-reverse:,outline-size:,background-color:,pattern-text:,use-pattern-text:,pattern-outline:,use-pattern-outline:,pattern-overlay:,use-pattern-overlay:,use-shadow:,shadow-offset-x:,shadow-offset-y:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -82,157 +110,163 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -F | --font-name)
          FONT_NAME="$2"
-         shift 2
+         shift
          ;;
       -S | --font-size)
          FONT_SIZE="$2"
+         shift
          if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] ; then
             echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -S|--font-size!"
             exit 1
          fi
-         shift 2
          ;;
 
       -G | --blend-gradient-text)
          BLEND_GRADIENT_TEXT="$2"
-         shift 2
+         shift
          ;;
       -g | --blend-gradient-text-reverse)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         BLEND_GRADIENT_TEXT_REVERSE="$2"
+         shift
+         if [[ "${BLEND_GRADIENT_TEXT_REVERSE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             BLEND_GRADIENT_TEXT_REVERSE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${BLEND_GRADIENT_TEXT_REVERSE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             BLEND_GRADIENT_TEXT_REVERSE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -g|--blend-gradient-text-reverse!"
+            echo >&2 "ERROR: Invalid value ${BLEND_GRADIENT_TEXT_REVERSE} for -g|--blend-gradient-text-reverse!"
             exit 1
          fi
-         shift 2
          ;;
       -L | --blend-gradient-outline)
          BLEND_GRADIENT_OUTLINE="$2"
-         shift 2
+         shift
          ;;
       -l | --blend-gradient-outline-reverse)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         BLEND_GRADIENT_OUTLINE_REVERSE="$2"
+         shift
+         if [[ "${BLEND_GRADIENT_OUTLINE_REVERSE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             BLEND_GRADIENT_OUTLINE_REVERSE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${BLEND_GRADIENT_OUTLINE_REVERSE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             BLEND_GRADIENT_OUTLINE_REVERSE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -l|--blend-gradient-outline-reverse!"
+            echo >&2 "ERROR: Invalid value ${BLEND_GRADIENT_OUTLINE_REVERSE} for -l|--blend-gradient-outline-reverse!"
             exit 1
          fi
-         shift 2
          ;;
       -O | --outline-size)
          OUTLINE_SIZE="$2"
+         shift
          if [[ ! "${OUTLINE_SIZE}" =~ ^[0-9]+$ ]] || [ "${OUTLINE_SIZE}" -lt 2 ] || [ "${OUTLINE_SIZE}" -gt 250 ] ; then
             echo >&2 "ERROR: Invalid value ${OUTLINE_SIZE} for -O|--outline-size!"
             exit 1
          fi
-         shift 2
          ;;
       -B | --background-color)
          BACKGROUND_COLOR="$2"
-         shift 2
+         shift
          ;;
 
       -I | --pattern-text)
          PATTERN_TEXT="$2"
-         shift 2
+         shift
          ;;
       -i | --use-pattern-text)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_PATTERN_TEXT="$2"
+         shift
+         if [[ "${USE_PATTERN_TEXT}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_PATTERN_TEXT="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_PATTERN_TEXT}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_TEXT="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -i|--use-pattern-text!"
+            echo >&2 "ERROR: Invalid value ${USE_PATTERN_TEXT} for -i|--use-pattern-text!"
             exit 1
          fi
-         shift 2
          ;;
       -J | --pattern-outline)
          PATTERN_OUTLINE="$2"
-         shift 2
+         shift
          ;;
       -j | --use-pattern-outline)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_PATTERN_OUTLINE="$2"
+         shift
+         if [[ "${USE_PATTERN_OUTLINE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_PATTERN_OUTLINE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_PATTERN_OUTLINE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_OUTLINE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -j|--use-pattern-outline!"
+            echo >&2 "ERROR: Invalid value ${USE_PATTERN_OUTLINE} for -j|--use-pattern-outline!"
             exit 1
          fi
-         shift 2
          ;;
       -R | --pattern-overlay)
          PATTERN_OVERLAY="$2"
-         shift 2
+         shift
          ;;
       -r | --use-pattern-overlay)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_PATTERN_OVERLAY="$2"
+         shift
+         if [[ "${USE_PATTERN_OVERLAY}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_PATTERN_OVERLAY="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_PATTERN_OVERLAY}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_PATTERN_OVERLAY="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -r|--use-pattern-overlay!"
+            echo >&2 "ERROR: Invalid value ${USE_PATTERN_OVERLAY} for -r|--use-pattern-overlay!"
             exit 1
          fi
-         shift 2
          ;;
 
       -s | --use-shadow)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         USE_SHADOW="$2"
+         shift
+         if [[ "${USE_SHADOW}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             USE_SHADOW="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${USE_SHADOW}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             USE_SHADOW="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -s|--use-shadow!"
+            echo >&2 "ERROR: Invalid value ${USE_SHADOW} for -s|--use-shadow!"
             exit 1
          fi
-         shift 2
          ;;
       -X | --shadow-offset-x)
          SHADOW_OFFSET_X="$2"
+         shift
          if [[ ! "${SHADOW_OFFSET_X}" =~ ^[0-9]+$ ]] || [ "${SHADOW_OFFSET_X}" -lt 1 ] || [ "${SHADOW_OFFSET_X}" -gt 100 ] ; then
             echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_X} for -X|--shadow-offset-x!"
             exit 1
          fi
-         shift 2
          ;;
-      -Y | --shadow-offet-y)
+      -Y | --shadow-offset-y)
          SHADOW_OFFSET_Y="$2"
+         shift
          if [[ ! "${SHADOW_OFFSET_Y}" =~ ^[0-9]+$ ]] || [ "${SHADOW_OFFSET_Y}" -lt 1 ] || [ "${SHADOW_OFFSET_Y}" -gt 100 ] ; then
-            echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_Y} for -Y|--shadow-offet-y!"
+            echo >&2 "ERROR: Invalid value ${SHADOW_OFFSET_Y} for -Y|--shadow-offset-y!"
             exit 1
          fi
-         shift 2
          ;;
 
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -243,14 +277,17 @@ TEXT="$2"
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || command -v /Applications/GIMP.app/Contents/MacOS/gimp-console-3 || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
-   echo >&2 "ERROR: GIMP is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
-   echo >&2 "* Fedora:  sudo dnf install -y gimp"
-   echo >&2 "* SuSE     sudo zypper install -y gimp"
-   echo >&2 "* Alpine:  sudo apk add gimp"
-   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
+   echo >&2 "ERROR: GIMP is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y gimp"
+   echo >&2 " * Fedora:        sudo dnf install -y gimp"
+   echo >&2 " * SuSE           sudo zypper install -y gimp"
+   echo >&2 " * Alpine:        sudo apk add gimp"
+   echo >&2 " * FreeBSD:       sudo pkg install -y gimp3-app"
+   echo >&2 " * NetBSD:        sudo pkgin -y install gimp"
+   echo >&2 " * OpenBSD:       sudo pkg_add gimp"
+   echo >&2 " * Apple:         brew install gimp"
    exit 1
 fi
 GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
@@ -716,7 +753,7 @@ rm -f "${OUTPUT_FILENAME}"
       (set! font "${FONT_NAME}"))
    ; (newline) (display "font=") (display font) (newline)
    (if (and (not (defined? 'gimp-image-get-active-layer)) (= font -1)) (
-      (gimp-message "ERROR: Font \"${FONT_NAME}\" is not available! Check installed fonts using fc-list!")
+      (gimp-message "ERROR: Font \"${FONT_NAME}\" is not available! Check installed fonts with gs-list-fonts!")
       (quit FALSE)
    ))
 
@@ -832,7 +869,7 @@ EOF
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
diff --git a/src/background/gimp-scripts/gs-resize-with-cropping b/src/background/gimp-scripts/gs-resize-with-cropping
--- a/src/background/gimp-scripts/gs-resize-with-cropping
+++ b/src/background/gimp-scripts/gs-resize-with-cropping
@@ -42,7 +42,7 @@ usage () {
 
 # ###### Version ############################################################
 version () {
-   echo "gs-resize-with-cropping @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   echo "gs-resize-with-cropping 2.7.5~rc0"
    exit 0
 }
 
@@ -51,8 +51,32 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o A:W:H:wqhv --long aspect:,width:,height:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -68,27 +92,24 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -A | --aspect)
          ASPECT="$2"
-         shift 2
+         shift
          ;;
       -W | --width)
          NEW_WIDTH="$2"
-         shift 2
+         shift
          ;;
       -H | --height)
          NEW_HEIGHT="$2"
-         shift 2
+         shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
@@ -98,9 +119,12 @@ while [ $# -gt 0 ] ; do
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -143,7 +167,7 @@ fi
 
 
 # ====== Detect GraphicsMagick ==============================================
-GM="$(which gm 2>/dev/null || true)"
+GM="$(command -v gm || true)"
 if [ "${GM}" == "" ] ; then
    echo >&2 "ERROR: GraphicsMagick is not installed! Try:"
    echo >&2 " * Ubuntu/Debian: sudo apt install -y graphicsmagick"
@@ -151,6 +175,9 @@ if [ "${GM}" == "" ] ; then
    echo >&2 " * SuSE:          sudo zypper install -y GraphicsMagick"
    echo >&2 " * Alpine:        sudo apk add graphicsmagick"
    echo >&2 " * FreeBSD:       sudo pkg install -y GraphicsMagick"
+   echo >&2 " * NetBSD:        sudo pkgin -y install GraphicsMagick"
+   echo >&2 " * OpenBSD:       sudo pkg_add GraphicsMagick"
+   echo >&2 " * Apple:         brew install GraphicsMagick"
    exit 1
 fi
 
diff --git a/src/background/gimp-scripts/gs-test-gimp b/src/background/gimp-scripts/gs-test-gimp
--- a/src/background/gimp-scripts/gs-test-gimp
+++ b/src/background/gimp-scripts/gs-test-gimp
@@ -42,7 +42,7 @@ usage () {
 
 # ###### Version ############################################################
 version () {
-   echo "gs-test-gimp @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   echo "gs-test-gimp 2.7.5~rc0"
    exit 0
 }
 
@@ -51,8 +51,32 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt)"
+      ;;
+esac
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o wqhv --long verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -66,27 +90,27 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 0 ] ; then
@@ -114,14 +138,17 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || command -v /Applications/GIMP.app/Contents/MacOS/gimp-console-3 || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
-   echo >&2 "ERROR: GIMP is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
-   echo >&2 "* Fedora:  sudo dnf install -y gimp"
-   echo >&2 "* SuSE     sudo zypper install -y gimp"
-   echo >&2 "* Alpine:  sudo apk add gimp"
-   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
+   echo >&2 "ERROR: GIMP is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y gimp"
+   echo >&2 " * Fedora:        sudo dnf install -y gimp"
+   echo >&2 " * SuSE           sudo zypper install -y gimp"
+   echo >&2 " * Alpine:        sudo apk add gimp"
+   echo >&2 " * FreeBSD:       sudo pkg install -y gimp3-app"
+   echo >&2 " * NetBSD:        sudo pkgin -y install gimp"
+   echo >&2 " * OpenBSD:       sudo pkg_add gimp"
+   echo >&2 " * Apple:         brew install gimp"
    exit 1
 fi
 GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
@@ -132,9 +159,6 @@ else
    # GIMP 3.x:
    GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 fi
-
-# This script does not use fonts, or gradients/palettes/brushes:
-GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
 
 
 # ====== Try to start GIMP ==================================================
@@ -147,6 +171,6 @@ EOF
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
