Improved scripts.

diff --git a/src/background/gimp-scripts/Make-Caption b/src/background/gimp-scripts/Make-Caption
--- a/src/background/gimp-scripts/Make-Caption
+++ b/src/background/gimp-scripts/Make-Caption
@@ -28,11 +28,60 @@ set -e
 
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 6 ] ; then
-   echo >&2 "Usage: $0 output_filename caption_text caption_width caption_height font font_size_percent [foreground [background [transparency]]]"
-   exit 1
-fi
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 output_filename caption_text caption_width caption_height font font_size_percent [--foreground|-f color] [--background|-b color] [--transparency|-t percentage] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Caption.png \"Caption Text\" 1024 42 \"Noto Sans Bold\" 60 \"#02266b\" \"#ffd700\" 26"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o f:b:t:vqh --long foreground:,background:,transparency:,verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
+
+COLOR_FOREGROUND="#02266b"   # Dark Blue
+COLOR_BACKGROUND="#ffd700"   # Gold
+TRANSPARENCY=25              # %
 VERBOSE=1
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -f | --foreground)
+         COLOR_FOREGROUND="$2"
+         shift 2
+         ;;
+      -b | --background)
+         COLOR_BACKGROUND="$2"
+         shift 2
+         ;;
+      -t | --transparency)
+         TRANSPARENCY="$2"
+         shift 2
+         ;;
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
+if [ $# -lt 6 ] ; then
+   usage 1
+fi
 OUTPUT_FILENAME="$1"
 CAPTION_TEXT="$2"
 CAPTION_WIDTH=$3
@@ -40,24 +89,38 @@ CAPTION_HEIGHT=$4
 FONT_NAME="$5"
 FONT_SIZE=$6
 
-COLOR_FOREGROUND="#02266b"   # Dark Blue
-COLOR_BACKGROUND="#ffd700"   # Gold
-TRANSPARENCY=25              # %
-if [ $# -gt 6 ] ; then
-   COLOR_FOREGROUND="$7"
-   if [ $# -gt 7 ] ; then
-      COLOR_BACKGROUND="$8"
-      if [ $# -gt 8 ] ; then
-         TRANSPARENCY="$9"
-      fi
-   fi
+if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ ${TRANSPARENCY} -lt 0 ] || [ ${TRANSPARENCY} -gt 100 ] ; then
+   echo >&2 "ERROR: Invalid transparency value!"
+   exit 1
+fi
+if [[ ! "${CAPTION_WIDTH}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid caption width!"
+   exit 1
+fi
+if [[ ! "${CAPTION_HEIGHT}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid caption height!"
+   exit 1
 fi
 
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
 
 # ====== Call GIMP ==========================================================
 rm -f "${OUTPUT_FILENAME}"
 ( cat <<EOF
 (let*
+   ; ------ Initialise and load image ---------------------------------------
    ((outputFileName   "${OUTPUT_FILENAME}")
     (captionText      "${CAPTION_TEXT}")
     (captionWidth     ${CAPTION_WIDTH})
@@ -94,7 +157,7 @@ rm -f "${OUTPUT_FILENAME}"
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp --quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch - 2>&1 | \
+) | env LANG=C HOME=/tmp gimp ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
