Updated scripts.

diff --git a/src/background/gimp-scripts/Make-Background b/src/background/gimp-scripts/Make-Background
--- a/src/background/gimp-scripts/Make-Background
+++ b/src/background/gimp-scripts/Make-Background
@@ -39,7 +39,7 @@ GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 options="$(${GETOPT} -o vqh --long verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
-VERBOSE=1
+VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
       -v | --verbose)
@@ -72,6 +72,21 @@ OUTPUT_FILENAME="$2"
 if [ ! -f "${INPUT_FILENAME}" ] ; then
    echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
+fi
+
+
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 fi
 
 
@@ -134,20 +149,20 @@ rm -f "${OUTPUT_FILENAME}"
    )
    (else
       ; Old Gimp 2.x API:
-      (file-png-save2 RUN-NONINTERACTIVE image layer outputFileName outputFileName TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE
+      (file-png-save2 RUN-NONINTERACTIVE image (car (gimp-image-get-active-layer image)) outputFileName outputFileName TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE
    )))
 
    ; ------ Clean up --------------------------------------------------------
    (gimp-image-delete image)
-   (gimp-quit TRUE)
 )
+(gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch - 2>&1 | \
+) | env LANG=C HOME=/tmp gimp ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|^Welcome|^using gegl copy|scriptfu-WARNING|LibGimp-WARNING|^Please use named arguments:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|^Welcome|^using gegl copy|scriptfu-WARNING|LibGimp-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
