Updated background scripts.

diff --git a/src/background/gimp-scripts/Make-OilPainting b/src/background/gimp-scripts/Make-OilPainting
--- a/src/background/gimp-scripts/Make-OilPainting
+++ b/src/background/gimp-scripts/Make-OilPainting
@@ -1,7 +1,17 @@
 #!/usr/bin/env bash
+# ==========================================================================
+#         ____            _                     _____           _
+#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
+#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
+#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
+#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
+#               |___/
+#                             --- System-Tools ---
+#                  https://www.nntb.no/~dreibh/system-tools/
+# ==========================================================================
 #
-# Background Script
-# Copyright (C) 2017-2025 by Thomas Dreibholz
+# GIMP Scripts
+# Copyright (C) 2013-2025 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -9,7 +19,7 @@
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY# without even the implied warranty of
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
@@ -23,25 +33,43 @@ set -eu
 
 
 # Example:
-# Make-Background Demo-Fractal-8192x6144.png Background1.png
+# Make-OilPainting Image1.jpeg Painting1.png
+# Make-OilPainting Image1.jpeg Painting2.png --masksize 5
 
 
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename [--verbose|-v] [--quiet|-q] [--help|-h]"
-   echo >&2 "Example: $0 Demo-Fractal-8192x6144.png Background1.png"
+   echo >&2 "Usage: $0 input_filename output_filename [--masksize|-s masksize] [--mode|-m rgb|intensity] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Image.jpeg Cloth.png --masksize 5"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o vqh --long verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o s:m:vqh --long masksize:,mode:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
+MASKSIZE=8
+MODE=1
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
+      -s | --masksize)
+         MASKSIZE="$2"
+         shift 2
+         ;;
+      -m | --mode)
+         if [ "$2" == "rgb" ] ; then
+            MODE=0
+         elif [ "$2" == "intensity" ] ; then
+            MODE=1
+         else
+            echo >&2 "ERROR: Invalid mode!"
+            exit 1
+         fi
+         shift 2
+         ;;
       -v | --verbose)
          VERBOSE=1
          shift
@@ -73,6 +101,10 @@ if [ ! -f "${INPUT_FILENAME}" ] ; then
    echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
 fi
+if [[ ! "${MASKSIZE}" =~ ^([0-9]+)$ ]] ; then
+   echo >&2 "ERROR: Invalid mask size ${MASKSIZE}!"
+   exit 1
+fi
 
 
 # ====== Obtain GIMP call options ===========================================
@@ -101,6 +133,8 @@ rm -f "${OUTPUT_FILENAME}"
    ; ------ Initialise and load image ---------------------------------------
    ((inputFileName    "${INPUT_FILENAME}")
     (outputFileName   "${OUTPUT_FILENAME}")
+    (maskSize         ${MASKSIZE})
+    (mode             ${MODE})
     (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
     (imageType        (if (not (defined? 'gimp-image-get-active-layer))
                          ; New Gimp 3.0 API:
@@ -118,51 +152,25 @@ rm -f "${OUTPUT_FILENAME}"
 
    ; ------ Apply filter ----------------------------------------------------
    ; First, make sure that the image is RGB, not indexed color mode!
-   (if (defined? 'gimp-drawable-hue-saturation)
-      (begin  ; New Gimp > 2.8 API:
-         ; New Gimp > 2.8 API:
-         (gimp-drawable-hue-saturation layer HUE-RANGE-ALL 120.0 0 0 0)
-      )
-      (begin  ; Old Gimp <= 2.8 API:
-         (gimp-hue-saturation layer ALL-HUES 120.0 0 0)
+   (if (not (= RGB imageType))
+      (gimp-image-convert-rgb image))
+
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   ; GEGL Oilify options: https://gegl.org/operations/gegl-oilify.html
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+   (cond( (not(defined? 'plug-in-mosaic))
+      ; New Gimp 3.0 API:
+      (gimp-drawable-merge-new-filter layer "gegl:oilify" 0 LAYER-MODE-REPLACE 1.0
+          "mask-radius" (max 1 (/ maskSize 2))
+          "use-inten"   mode
       )
    )
-
-   ; Step 2: Apply Bump Map effect
-   (if (defined? 'gimp-drawable-merge-new-filter)
-      (begin  ; New Gimp >= 3.0 API:
-        (gimp-drawable-merge-new-filter layer "gegl:bump-map" 0 LAYER-MODE-REPLACE 1.0
-            "azimuth"         30.0
-            "elevation"       45.0
-            "depth"           20.0
-            "offset-x"        0
-            "offset-y"        0
-            "waterlevel"      0.0
-            "ambient"         0.0
-            "compensate"      TRUE
-            "invert"          FALSE
-            "type"            "linear"
-        )
-      )
-      (begin  ; Old Gimp < 3.0 API:
-         (plug-in-bump-map RUN-NONINTERACTIVE image layer layer
-           30.0 45.0 20
-           0 0 0 0
-           TRUE FALSE 0)
-      )
-   )
-
-   ; Step 3: Darken the result a little bit
-   (if (defined? 'gimp-drawable-hue-saturation)
-      (begin  ; New Gimp > 2.8 API:
-         ; New Gimp > 2.8 API:
-         (gimp-drawable-hue-saturation layer HUE-RANGE-ALL 0 -15 0 0)
-      )
-      (begin  ; Old Gimp <= 2.8 API:
-         (gimp-hue-saturation layer ALL-HUES 0 -15 0)
-      )
-   )
-
+   (else
+      ; Old Gimp 2.x API:
+      (display maskSize) (newline)
+      (plug-in-oilify RUN-NONINTERACTIVE image layer maskSize mode)
+   ))
 
    ; ------ Save result -----------------------------------------------------
    (if (defined? 'gimp-drawable-merge-new-filter)
diff --git a/src/background/gimp-scripts/run-tests b/src/background/gimp-scripts/run-tests
--- a/src/background/gimp-scripts/run-tests
+++ b/src/background/gimp-scripts/run-tests
@@ -1,18 +1,62 @@
 #!/usr/bin/env bash
+# ==========================================================================
+#         ____            _                     _____           _
+#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
+#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
+#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
+#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
+#               |___/
+#                             --- System-Tools ---
+#                  https://www.nntb.no/~dreibh/system-tools/
+# ==========================================================================
+#
+# GIMP Scripts
+# Copyright (C) 2013-2025 by Thomas Dreibholz
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+# Contact: thomas.dreibholz@gmail.com
 
+# Bash options:
 set -eux
 
-INPUT1="../Input/Zollverein.jpeg"
-INPUT2="../Input/Background.png"
+
+INPUT1="examples/Bergen.jpeg"
+INPUT2="examples/Background.png"
+
+# ------ Use FractGen to generate the example image -------------------------
+# Requires: clifractgen
+if [ ! -e "${INPUT2}"  ] ; then
+   if [ -e "/usr/share/fractgen/examples/alpha07.fsf" ] ; then
+      clifractgen  /usr/share/fractgen/examples/alpha07.fsf "${INPUT2}" -W 1920 -H 1080 -M 2048
+   elif [ -e "/usr/share/fractgen/examples/alpha07.fsf" ] ; then
+      clifractgen  /usr/local/share/fractgen/examples/alpha07.fsf "${INPUT2}" -W 1920 -H 1080 -M 2048
+   else
+      echo >&2 "ERROR: Input FSF file not found!"
+      exit 1
+   fi
+fi
 
 
-# ------ Make-Text ----------------------------------------------------------
-./Make-Text NorNet1.png "NorNet Testbed" 128
+# ------ Make-GlossyText ----------------------------------------------------
+./Make-GlossyText NorNet1.png "NorNet Testbed" 128
+
+./Make-GlossyText NorNet2.png "NorNet Testbed" 128 --bordersize 5 \
+   --colorscheme "Brushed Aluminium" --font "Noto Sans Bold"
 
 # Requires: fonts-lobster
-./Make-Text NorNet2.png "NorNet Testbed" 128 --bordersize 5 \
-   --colorscheme "Brushed Aluminium" --font "Noto Sans Bold"
-./Make-Text NorNet3.png "NorNet Testbed" 128 --bordersize 5 \
+./Make-GlossyText NorNet3.png "NorNet Testbed" 128 --bordersize 5 \
    --colorscheme "Golden" --font "Lobster Two Bold Italic" || true
 
 
@@ -22,8 +66,8 @@ INPUT2="../Input/Background.png"
 
 
 # ------ Make-<Conversion> Scripts ------------------------------------------
-./Resize-with-Cropping "${INPUT1}" Image1.png 16:9 1024
-./Resize-with-Cropping "${INPUT2}" Image2.png 16:9 1024
+./Resize-with-Cropping "${INPUT1}" Image1.png 16:9 1920
+./Resize-with-Cropping "${INPUT2}" Image2.png 16:9 1920
 
 
 ./Make-Mosaic Image1.png Mosaic1-H.png 24 4 4 --type hexagons --surface rough
@@ -35,8 +79,8 @@ INPUT2="../Input/Background.png"
 ./Make-Cloth Image1.png Cloth1.png
 ./Make-Cloth Image1.png Cloth2.png --depth 8
 
-./Make-Painting Image1.png Painting1.png --masksize 8 --mode intensity
-./Make-Painting Image1.png Painting2.png --masksize 8 --mode rgb
+./Make-OilPainting Image1.png Painting1.png --masksize 8 --mode intensity
+./Make-OilPainting Image1.png Painting2.png --masksize 8 --mode rgb
 
-./Make-Background Image2.png Background1.png
+./Make-BumpMap Image2.png Background1.png
 ./Make-Mosaic Background1.png Background2.png 18 4 4 --type hexagons --surface smooth --neatness 0.5
