Improved scripts.

diff --git a/src/background/gimp-scripts/Make-Text b/src/background/gimp-scripts/Make-Text
--- a/src/background/gimp-scripts/Make-Text
+++ b/src/background/gimp-scripts/Make-Text
@@ -28,38 +28,54 @@ set -e
 
 # Examples:
 # Make-Text NorNet1.png "NorNet Testbed" 128 --bordersize 5 --colorscheme Golden --font "Noto Sans Regular"
-# Make-Text NorNet2.png "NorNet Testbed" 128 --bordersize 5 --colorscheme "Brushed Aluminium" --font "Comic Sans MS"
+# Make-Text NorNet2.png "NorNet Testbed" 128 --bordersize 5 --colorscheme "Brushed Aluminium" --font "Comic Sans MS Bold"
+# Hint: List available fonts with "fc-list"!
 
 
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 filename content font_size [--bordersize|-b size] [--colorscheme|-c schemename] [--font|-f fontname] [--verbose|-v] [--quiet|-q] [--help|-h]"
-   echo >&2 "Example: $0 Image.jpeg Mosaic.png 24 4 4 --type hexagons --surface rough"
+   echo >&2 "Usage: $0 filename content font_size [--bordersize|-b size] [--colorscheme|-c schemename] [--font|-f fontname] [-p|--patterntext pattern] [-o|--patternoutline pattern] [-l|--patternoverlay pattern] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 NorNet1.png \"NorNet Testbed\" 128 --bordersize 5 --colorscheme Golden --font \"Noto Sans Regular\""
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o b:c:f:vqh --long bordersize:,colorscheme:,font:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o b:c:f:p:o:l:vqh --long bordersize:,colorscheme:,font:,patterntext:,patternoutline:,patternoverlay:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
-BORDERSIZE=5
+BORDER_SIZE=5
 COLORSCHEME="Golden"
-FONTNAME="Noto Sans Regular"
+FONT_NAME="Noto Sans Regular"
+PATTERN_TEXT="Electric Blue"
+PATTERN_OUTLINE="Electric Blue"
+PATTERN_OVERLAY="Parque #1"
 VERBOSE=1
 while [ $# -gt 0 ] ; do
    case "$1" in
       -b | --bordersize)
-         BORDERSIZE=$2
+         BORDER_SIZE="$2"
          shift 2
          ;;
       -c | --colorscheme)
-         COLORSCHEME=$2
+         COLORSCHEME="$2"
          shift 2
          ;;
       -f | --font)
-         FONTNAME="$2"
+         FONT_NAME="$2"
+         shift 2
+         ;;
+      -p | --patterntext)
+         PATTERN_TEXT="$2"
+         shift 2
+         ;;
+      -o | --patternoutline)
+         PATTERN_OUTLINE="$2"
+         shift 2
+         ;;
+      -l | --patternoverlay)
+         PATTERN_OVERLAY="$2"
          shift 2
          ;;
       -v | --verbose)
@@ -88,14 +104,14 @@ if [ $# -lt 3 ] ; then
 fi
 OUTPUT_FILENAME="$1"
 CONTENT="$2"
-FONTSIZE=$3
+FONT_SIZE=$3
 
-if [[ ! "${FONTSIZE}" =~ ^[0-9]*$ ]] ; then
-   echo >&2 "ERROR: Invalid font size ${FONTSIZE}!"
+if [[ ! "${FONT_SIZE}" =~ ^[0-9]*$ ]] ; then
+   echo >&2 "ERROR: Invalid font size ${FONT_SIZE}!"
    exit 1
 fi
-if [[ ! "${BORDERSIZE}" =~ ^[0-9]*$ ]] ; then
-   echo >&2 "ERROR: Invalid border size ${BORDERSIZE}!"
+if [[ ! "${BORDER_SIZE}" =~ ^[0-9]*$ ]] ; then
+   echo >&2 "ERROR: Invalid border size ${BORDER_SIZE}!"
    exit 1
 fi
 
@@ -476,8 +492,8 @@ rm -f "${OUTPUT_FILENAME}"
    ((outputFileName   "${OUTPUT_FILENAME}")
     (logoText    "$CONTENT")
     (font)
-    (fontSize     $FONTSIZE)
-    (borderSize   $BORDERSIZE)
+    (fontSize     $FONT_SIZE)
+    (borderSize   $BORDER_SIZE)
     (colorScheme)
     (patternText)
     (patternOutline)
@@ -490,29 +506,34 @@ rm -f "${OUTPUT_FILENAME}"
    )
 
    (if (not (defined? 'gimp-image-get-active-layer))
-      (set! font (car (gimp-font-get-by-name "$FONTNAME")))
-      (set! font "$FONTNAME"))
+      (set! font (car (gimp-font-get-by-name "$FONT_NAME")))
+      (set! font "$FONT_NAME"))
    (display "font=") (display font) (newline)
+   (if (= font -1) ( (gimp-message "ERROR: Font \"$FONT_NAME\" is not available! Check installed fonts with fc-list!") (quit FALSE) ))
 
    (if (not (defined? 'gimp-image-get-active-layer))
-      (set! colorScheme (car (gimp-gradient-get-by-name "$COLORSCHEME")))
-      (set! colorScheme "$COLORSCHEME"))
+      (set! colorScheme (car (gimp-gradient-get-by-name "${COLORSCHEME}")))
+      (set! colorScheme "${COLORSCHEME}"))
    (display "colorScheme=") (display colorScheme) (newline)
+   (if (= colorScheme -1) ( (gimp-message "ERROR: Color scheme \"${COLORSCHEME}\" is not available!") (quit FALSE) ))
 
    (if (not (defined? 'gimp-image-get-active-layer))
-      (set! patternText (car (gimp-pattern-get-by-name "Electric Blue")))
-      (set! patternText "Electric Blue"))
+      (set! patternText (car (gimp-pattern-get-by-name "${PATTERN_TEXT}")))
+      (set! patternText "${PATTERN_TEXT}"))
    (display "patternText=") (display patternText) (newline)
+   (if (= patternText -1) ( (gimp-message "ERROR: Pattern \"${PATTERN_TEXT}\" is not available!") (quit FALSE) ))
 
    (if (not (defined? 'gimp-image-get-active-layer))
-      (set! patternOutline (car (gimp-pattern-get-by-name "Electric Blue")))
-      (set! patternOutline "Electric Blue"))
+      (set! patternOutline (car (gimp-pattern-get-by-name "${PATTERN_OUTLINE}")))
+      (set! patternOutline "${PATTERN_OUTLINE}"))
    (display "patternOutline=") (display patternOutline) (newline)
+   (if (= patternOutline -1) ( (gimp-message "ERROR: Pattern \"${PATTERN_OUTLINE}\" is not available!") (quit FALSE) ))
 
    (if (not (defined? 'gimp-image-get-active-layer))
-      (set! patternOverlay (car (gimp-pattern-get-by-name "Parque #1")))
-      (set! patternOverlay "Parque #1"))
+      (set! patternOverlay (car (gimp-pattern-get-by-name "${PATTERN_OVERLAY}")))
+      (set! patternOverlay "${PATTERN_OVERLAY}"))
    (display "patternOverlay=") (display patternOverlay) (newline)
+   (if (= patternOverlay -1) ( (gimp-message "ERROR: Pattern \"${PATTERN_OVERLAY}\" is not available!") (quit FALSE) ))
 
    (set! image (car (script-fu-glossy-300-logo logoText fontSize font 0 8 8 colorScheme FALSE colorScheme FALSE borderSize "white" FALSE patternText FALSE patternOutline FALSE patternOverlay TRUE TRUE 8 8)))
    (display "image=") (display image) (newline)
@@ -570,12 +591,12 @@ rm -f "${OUTPUT_FILENAME}"
    (gimp-quit TRUE)
 )
 EOF
-) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch - 2>&1 | \
+) | env LANG=C HOME=/tmp gimp --quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch - 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|^Welcome|^using gegl copy|scriptfu-WARNING|LibGimp-WARNING|^Please use named arguments:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|^Welcome|^using gegl copy|scriptfu-WARNING|LibGimp-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
