Improved scripts.

diff --git a/src/background/gimp-scripts/Make-Mosaic b/src/background/gimp-scripts/Make-Mosaic
--- a/src/background/gimp-scripts/Make-Mosaic
+++ b/src/background/gimp-scripts/Make-Mosaic
@@ -147,6 +147,22 @@ if [[ ! "${LIGHT_DIRECTION}" =~ ^[0-9]+$ ]] ; then
    exit 1
 fi
 
+
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
+
+
 # ====== Call GIMP ==========================================================
 rm -f "${OUTPUT_FILENAME}"
 ( cat <<EOF
@@ -240,7 +256,7 @@ rm -f "${OUTPUT_FILENAME}"
    (gimp-quit TRUE)
 )
 EOF
-) | env LANG=C HOME=/tmp gimp --quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch - 2>&1 | \
+) | env LANG=C HOME=/tmp gimp ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
