Improved script.

diff --git a/src/background/gimp-scripts/Make-Mosaic b/src/background/gimp-scripts/Make-Mosaic
--- a/src/background/gimp-scripts/Make-Mosaic
+++ b/src/background/gimp-scripts/Make-Mosaic
@@ -23,14 +23,20 @@ set -eu
 
 
 # Example:
-# Make-Mosaic Image.jpeg Mosaic.png 24 4 4 hexagons rough
-# Make-Mosaic Image.jpeg Mosaic.png 32 4 2 octagons smooth
+# Make-Mosaic Image.jpeg Mosaic.png 24 4 4 --type hexagons --surface rough
+# Make-Mosaic Image.jpeg Mosaic.png 32 4 2 --type octagons --surface smooth
 
 
 # ====== Handle arguments ===================================================
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 input_filename output_filename tile_size tile_height tile_spacing [-t|--type squares|hexagons|octagons|triangles] [-s|--surface smooth|rough] [-n|--neatness neatness] [-l|--lightdirection direction] [-c|--colorvariation variation] [--verbose|-v] [--quiet|-q]"
+   echo >&2 "Example: $0 Image.jpeg Mosaic.png 24 4 4 --type hexagons --surface rough"
+   exit "${exitCode}"
+}
+
 if [ $# -lt 5 ] ; then
-   echo >&2 "Usage: $0 input_filename output_filename tile_size tile_height tile_spacing [squares|hexagons|octagons|triangles [smooth|rough]]"
-   exit 1
+   usage
 fi
 INPUT_FILENAME="$1"
 OUTPUT_FILENAME="$2"
@@ -38,35 +44,114 @@ TILE_SIZE=$3
 TILE_HEIGHT=$4
 TILE_SPACING=$5
 TILE_NEATNESS=0.65
-TILE_TYPE="6"
 TILE_TYPESTRING="hexagons"
+TILE_TYPE="6"
 TILE_SURFACE=0
+LIGHT_DIRECTION=135
+COLOR_VARIATION=0.2
 VERBOSE=0
-if [ $# -gt 5 ] ; then
-   TILE_TYPESTRING="$6"
-   if [ "${TILE_TYPESTRING}" = "squares" ] ; then
-      TILE_TYPE=0
-   elif [ "${TILE_TYPESTRING}" = "hexagons" ] ; then
-      TILE_TYPE=1
-   elif [ "${TILE_TYPESTRING}" = "octagons" ] ; then
-      TILE_TYPE=2
-   elif [ "${TILE_TYPESTRING}" = "triangles" ] ; then
-      TILE_TYPE=3
-   else
-      echo >&2 "Invalid tile type: ${TILE_TYPESTRING}"
-      exit 1
-   fi
+shift 5
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o t:s:n:l:c:vqh --long type,surface,neatness,lightdirection,colorvariation,verbose,quiet,help -a -- $@)"
+# shellcheck disable=SC2181
+if [[ $? -ne 0 ]] ; then
+   usage 1
 fi
-if [ $# -gt 6 ] ; then
-   if [ "$7" = "smooth" ] ; then
-      TILE_SURFACE=0
-   elif [ "$7" = "rough" ] ; then
-      TILE_SURFACE=1
-   else
-      echo >&2 "Invalid tile surface: $7"
-      exit 1
-   fi
+
+eval set -- "${options}"
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -t | --type)
+         TILE_TYPESTRING="$2"
+         shift 2
+         ;;
+      -s | --surface)
+         if [ "$2" == "smooth" ] ; then
+            TILE_SURFACE=0
+         elif [ "$2" == "rough" ] ; then
+            TILE_SURFACE=1
+         else
+            echo >&2 "Invalid tile surface: $2"
+            exit 1
+         fi
+         shift 2
+         ;;
+      -n | --neatness)
+         TILE_NEATNESS="$2"
+         shift 2
+         ;;
+      -l | --lightdirection)
+         LIGHT_DIRECTION="$2"
+         shift 2
+         ;;
+      -c | --colorvariation)
+         COLOR_VARIATION="$2"
+         shift 2
+         ;;
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+if [ $# -gt 0 ] ; then
+   usage 1
 fi
+
+
+if [[ ! "${TILE_SIZE}" =~ ^[0-9]*$ ]] ; then
+   echo >&2 "ERROR: Invalid tile size!"
+   exit 1
+fi
+if [[ ! "${TILE_HEIGHT}" =~ ^[0-9]*$ ]] ; then
+   echo >&2 "ERROR: Invalid tile height!"
+   exit 1
+fi
+if [[ ! "${TILE_SPACING}" =~ ^[0-9]*$ ]] ; then
+   echo >&2 "ERROR: Invalid tile spacing!"
+   exit 1
+fi
+if [ "${TILE_TYPESTRING}" = "squares" ] ; then
+   TILE_TYPE=0
+elif [ "${TILE_TYPESTRING}" = "hexagons" ] ; then
+   TILE_TYPE=1
+elif [ "${TILE_TYPESTRING}" = "octagons" ] ; then
+   TILE_TYPE=2
+elif [ "${TILE_TYPESTRING}" = "triangles" ] ; then
+   TILE_TYPE=3
+else
+   echo >&2 "Invalid tile type: ${TILE_TYPESTRING}"
+   exit 1
+fi
+if [[ ! "${TILE_NEATNESS}" =~ ^[0-9]+(\.[0-9]*|)$ ]] ; then
+   echo >&2 "ERROR: Invalid tile neatness!"
+   exit 1
+fi
+if [[ ! "${COLOR_VARIATION}" =~ ^[0-9]+(\.[0-9]*|)$ ]] ; then
+   echo >&2 "ERROR: Invalid color variation!"
+   exit 1
+fi
+if [[ ! "${LIGHT_DIRECTION}" =~ ^[0-9]*$ ]] ; then
+   echo >&2 "ERROR: Invalid light direction!"
+   exit 1
+fi
+
 
 # ====== Call GIMP ==========================================================
 rm -f "${OUTPUT_FILENAME}"
@@ -82,6 +167,8 @@ rm -f "${OUTPUT_FILENAME}"
     (tileSpacing      ${TILE_SPACING})
     (tileNeatness     ${TILE_NEATNESS})
     (tileSurface      ${TILE_SURFACE})
+    (lightDirection   ${LIGHT_DIRECTION})
+    (colorVariation   ${COLOR_VARIATION})
     (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
     (layer            (if (not (defined? 'gimp-image-get-active-layer))
                          ; New Gimp 3.0 API:
@@ -96,6 +183,10 @@ rm -f "${OUTPUT_FILENAME}"
 ;   (if (not (= RGB (car (gimp-image-base-type image))))
 ;             (gimp-image-convert-rgb image))
 
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   ; GEGL Mosaic options: https://gegl.org/operations/gegl-mosaic.html
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
    (cond( (not(defined? 'plug-in-mosaic))
       ; New Gimp 3.0 API:
       (gimp-drawable-merge-new-filter layer "gegl:mosaic" 0 LAYER-MODE-REPLACE 1.0
@@ -104,10 +195,10 @@ rm -f "${OUTPUT_FILENAME}"
           "tile-spacing"    tileSpacing
           "tile-neatness"   tileNeatness
           "antialiasing"    TRUE
-          "light-dir"       135
-          "color-variation" 0.2
+          "light-dir"       lightDirection
+          "color-variation" colorVariation
           "tile-type"       tileTypeString
-          "tile-surface"    TRUE
+          "tile-surface"    tileSurface
           "seed"            0
       )
    )
@@ -115,7 +206,7 @@ rm -f "${OUTPUT_FILENAME}"
       ; Old Gimp 2.x API:
       (plug-in-mosaic RUN-NONINTERACTIVE image layer
          tileSize tileHeight tileSpacing
-         tileNeatness TRUE 135.0 0.2 TRUE TRUE
+         tileNeatness TRUE lightDirection colorVariation TRUE TRUE
          tileType tileSurface FALSE
    )))
 
@@ -158,6 +249,8 @@ EOF
    fi
 )
 
+
+# ====== Check result =======================================================
 if [ ! -e "${OUTPUT_FILENAME}" ] ; then
    echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
    exit 1
